  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cornell Society of Women Engineers</title>
    <link rel="icon" 
      type="image/ico" 
      href="SWEicon.ico">
    <link rel="stylesheet" href="stylesheets/app.css" />
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <script src="bower_components/modernizr/modernizr.js"></script>
  </head>