<!-- HEADER -->
<iframe src="header.asp" width="100%" height="500" scrolling="auto" frameborder="0"></iframe>

<!-- CONTENTS -->
<div id = "contents">


<div id = "contentsLeft">
<ul id = "menu">
<li><img src="imagesnew/ourprograms.png" alt="" />
            <ul>
           <li><a href="cd_main.asp">Career Development</a></li>
           <li><a href="cr_main.asp">Corporate Relations</a></li>
           <li><a href="outreach_main.asp">Outreach</a></li>
           <li><a href="pr_main.asp">Public Relations</a></li>
           <li><a href="student_services.asp">Student Services</a></li>
           <li><a href="finance.asp">Finance</a></li>
           <li><a href="fundraising.asp">Fundraising</a></li>
           <li><a href="gsp_main.asp">Graduate Student Program</a></li>
           </ul>
</li>
</ul>
</div> <!-- END CONTENTS LEFT DIV -->

<div id="contentsMain">
<h1>Welcome to Cornell SWE!</h1>

		<p>
		<iframe src="http://www.google.com/calendar/embed?mode=AGENDA&amp;src=swe.cornell%40gmail.com&ctz=America/New_York" style="border: 0" width="510" height="600" frameborder="0" scrolling="no"></iframe>
		
	</div> <!-- END CONTENTS MAIN -->



<div id = "contentsRight">
<ul id = "menu">
<li><img src="imagesnew/formembers.png" alt=""" />
            <ul>
           <li><a href="get_involved.asp">get involved</a></li>
           <li><a href="scholarships.asp">scholarship opportunities</a></li>
           <li><a href="docs.asp">documents</a></li>
           <li><a href="newsletter.asp">newsletters</a></li>
           <li><a href="photos.asp">photos</a></li>
           <li><a href="resources.asp">resources</a></li>
           </ul>
</li>

<br />

<li><img src="imagesnew/foremployers.png" alt=""" />
           <ul>
           <li><a href="info_session.asp">host an information session</a></li>
           <li><a href="pnd_main.asp">professional networking reception</a></li>
           <li><a href="support.asp">support swe</a></li>
           <li><a href="sponsors.asp">our sponsors</a></li>
           </ul>
</li>
</ul>
</div> <!-- END CONTENTS RIGHT DIV -->


<!-- END INCLUDE -->