<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>Cornell Society of Women Engineers</title>
	<link type="text/css" rel="stylesheet" href="stylesheet.css" />
</head>

<body>

<div id="container">

<div id="menu2">
<img src="imagesnew/headersocial.png" alt="" border="0" id="topbanner" usemap="#socialmap" />
<map name="socialmap" id="socialmap">
	<area shape="rect" coords="0, 0, 604, 67" href="index.asp" target="_parent" />
	<area shape="rect" coords="685, 26, 719, 59" href="https://www.facebook.com/CornellSwe" target="_blank" />
	<area shape="rect" coords="727, 25, 761, 58" href="https://twitter.com/CornellSWE1" target="_blank" />
	<area shape="rect" coords="768, 28, 803, 60" href="http://www.youtube.com/user/CornellSWE" target="_blank" />
	<area shape="rect" coords="811, 26, 848, 59" href="http://www.linkedin.com/groups?gid=2408656" target="_blank" />
</map>

<br /><br />
<img src="imagesnew/banner_h.png" alt="" border="0" usemap="#navmap" />

<map name="navmap" id="navmap">
  <area shape="rect" coords="490, 0, 560, 30" href="index.asp" target="_parent" alt="home" />
  <area shape="rect" coords="560, 0, 640, 30" href="about_main.asp" target="_parent" alt="about" />
  <area shape="rect" coords="640, 0, 740, 30" href="join.asp" target="_parent" alt="join swe" />
  <area shape="rect" coords="740, 0, 840, 40" href="contact.asp" target="_parent" alt="contact us" />
</map>
</div>



<div id="sidebar">

<h2>Our Programs</h2>
 <ul>
           <li><a href="cd_main.asp">Career Development</a></li>
           <li><a href="cr_main.asp">Corporate Relations</a></li>
           <li><a href="outreach_main.asp">Outreach</a></li>
           <li><a href="pr_main.asp">Public Relations</a></li>
           <li><a href="student_services.asp">Student Services</a></li>
           <li><a href="finance.asp">Finance Forms</a></li>
           <li><a href="fundraising.asp">Fundraising</a></li>
           <li><a href="gsp_main.asp">Graduate Student Program</a></li>
           </ul>
		   
		   
		   <h2>For Members</h2>
		     <ul>
           <li><a href="get_involved.asp">Get Involved</a></li>
           <li><a href="scholarships.asp">Scholarship Opportunities</a></li>
           <li><a href="docs.asp">Documents</a></li>
           <li><a href="newsletter.asp">Newsletters</a></li>
           <li><a href="photos.asp">Photos</a></li>
           <li><a href="resources.asp">Resources</a></li>
		 		   <li><a href="http://facebook.com/groups/2200096715?ap=1">Facebook group</a></li>
		   <li><a href="http://www.linkedin.com/groups?viewMembers=&gid=2408656&sik=1317843674949">LinkedIn Group</a></li>
		     <li><a href="merchandise.asp">Merchandise</a></li>
           </ul>
		   
		   
		   <h2>For Employers</h2>
		    <ul>
           <li><a href="info_session.asp">Host An Information Session</a></li>
           <li><a href="pnd_main.asp">Professional Networking Dinner</a></li>
           <li><a href="support.asp">Support SWE</a></li>
           <li><a href="sponsors.asp">Our Sponsors</a></li>
           </ul>

		   <h2>For Alumni</h2>
		   <ul><span style="color:#545454">Coming Soon!</span></ul><br/>
</div>




<div id = "main">