<!-- Begin Menu -->


<a href="index.asp"><img id="topbanner" src = "imagesnew/banner.jpg" alt = "Society of Women Engineers"/></a>
	
	<div id = "inner">
	
	<div id = "menuLeft">
		<img src = "imagesnew/header_menu.jpg" alt="Menu"/>
		<ul>
			<li><a href="index.asp">Home</a></li>
			<li><a href="about_main.asp">About Us</a></li>
			<li><a href="programs.asp">Our Programs</a></li>
			<li><a href="pnd_main.asp">PNR</a></li>
			<li><a href="outreach_main.asp">Outreach</a></li>
			<li><ul>
				<li><font class="menuLeftSub"><a href="outreach_chair.asp">For Chairs</a></font></li>
            	<li><font class="menuLeftSub"><a href="outreach_contact.asp">Contact</a></font></li>
            </ul></li>
			<li><a href="cr_main.asp">Corporate Relations</a></li>
            <li><a href="newsletter.asp">Newsletter</a></li>
            <li><a href="support.asp">Support SWE</a></li>
            <li><a href="links.asp">External Links</a></li>
		</ul>
	</div> <!-- END div#menuLeft -->

	<div id = "menuRight">
		<img src = "imagesnew/header_quicklinks.jpg" alt = "Quick Links" />
		<ul>
			<li><img src="imagesnew/icon_pdf.gif" alt = "PDF"/><a href="newsletters/currentNews.pdf"> Current Newsletter</a></li>
			<li><a href="http://www.flickr.com/photos/cornell_swe/show/" target="_blank">Photos</a></li>
            <li><a href="docs.asp">Documents</a></li>
            <li><a href="commsheet.asp">Communication Sheets</a></li>
            <li><a href="publicity.asp">Publicity Procedure</a></li>                                   
            <li><a href="join.asp">Join SWE!</a></li>
			<li><img src="imagesnew/facebook-logo.png" alt="Facebook" /> <a href="http://www.facebook.com/group.php?gid=2200096715&ref=ts">Facebook Group</a></li>            <li><a href="/stress-relief">Stress Relief</a></li>
            <li><a href="contact.asp">Contact Us</a></li>
		</ul>
	</div> <!-- END div#menuRight -->

<!-- END MENU -->