
<h2>SWE Upcoming Events</h2>
<iframe src="https://www.google.com/calendar/b/0/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=swe.cornell%40gmail.com&amp;color=%232952A3&amp;ctz=America%2FNew_York" style=" border-width:0 " width="260" height="300" frameborder="0" scrolling="no"></iframe>

 </div>

<div id="footer">

<center>If you have any questions, contact us at <a href="#">corswe@gmail.com</a></center>
<br/>

<div id="footer1">
<h5>CORNELL SWE</h5>
162 Olin Hall<br/>
 Ithaca NY<br/>14853<br/><br/>
<a href="feedback.asp">Feedback</a> <br/><br/>
<a href="http://facebook.com/groups/2200096715?ap=1"><img src="imagesnew/facebook.png" width="20" height="20" alt="Facebook" title="Cornell SWE Facebook Group"/></a>
<a href="http://www.linkedin.com/groups?viewMembers=&gid=2408656&sik=1317843674949"><img src="imagesnew/linkedin.png" width="20" height="20" alt="LinkedIn" title="Cornell SWE LinkedIn Group"/></a>
<a href="http://www.flickr.com/photos/cornell_swe/sets"><img src="imagesnew/flickr.png" width="20" height="20" alt="Flickr" title="Cornell SWE Flickr Photos" /></a>
<a href="http://www.youtube.com/user/CornellSWE"><img src="imagesnew/youtube.png" width="20" height="20" alt="YouTube" title="Cornell SWE YouTube" /></a>
</div>

<div id="footer2">
<h5>LINKS</h5>
<a href="about_main.asp">About Us</a><br/>
<a href="contact.asp">Contact Us</a><br/>
<a href="http://swedirectors.blogspot.com/">SWE Blogspot</a><br/>
<a href="http://www.engineering.cornell.edu/diversity/">Cornell DPE</a><br/>
<a href="http://www.swe.org/regione/">SWE Region E</a><br/>
<a href="http://societyofwomenengineers.swe.org/">swe.org</a>
</div>


<div id="footer3">
<h5>JOIN SWE</h5>
<a href="join.asp">How to Join</a><br/>
<a href="chair.asp">Become a Chair</a><br/>
<a href="liaison.asp">Become a Liaison</a><br/>
<a href="director.asp">Become a Director</a><br/>
</div>

<div id="footer4">
<h5>UNDERGRADS</h5>
<a href="major.asp">Get a Major</a><br/>
<a href="study.asp">Get the "A"!</a><br/>
<a href="jobs.asp">Get a Job/Internship</a><br/>
<a href="scholarships.asp">Get a Scholarship</a><br/>
<a href="gradschool.asp">Get into Grad School</a><br/>
<a href="conferences.asp">Conferences</a><br/>
<a href="merchandise.asp">Merchandise</a><br/>
<a href="outreach_main.asp">Outreach</a><br/>
<a href="student_services.asp">Come Hang with Us!</a><br/>
<a href="chairs.asp">For Chairs</a><br/> 
</div>


<div id="footer5">
<h5>GRAD STUDENTS</h5>
<a href="gradoutreach.asp">Outreach</a><br/>
<a href="http://www.graduateswe.blogspot.com/">Grad SWE Blog</a><br/>
<a href="gsp_main.asp">Graduate Listserv</a><br/>
<a href="conferences.asp">Conferences</a><br/>
<a href="merchandise.asp">Merchandise</a><br/>
</div>

<div id="footer6">
<h5>EMPLOYERS</h5>
<a href="resumefile.asp">Resume file</a><br/>
<a href="info_session.asp">Information Session</a><br/>
<a href="pnd_main.asp">Professional Networking Dinner</a><br/>
 <a href="sponsors.asp">Our Sponsors</a><br/>
<a href="sponsorswe.asp">Support Cornell SWE</a><br/>
</div>

<div id="footer7">
<h5>ALUMNI</h5>
<a href="alumni_join.asp">Alumni Listserv</a><br/>
<a href="ted.asp">TED Talk</a><br/>
<a href="map.asp">Destination Map</a><br/>
<a href="alumniresources.asp">Resources</a><br/>
</div>



</div>
</div> 

</body>
</html>
