<!-- HEADER -->
<iframe src="header.asp" width="100%" height="500" scrolling="auto" frameborder="0"></iframe>


<!-- CONTENTS -->
<div id = "contents">



<div id = "contentsLeft">

<ul id = "menu">
<li><img src="imagesnew/ourprograms.png" alt="" />
           <ul>
           <li><a href="cd_main.asp">Career Development</a></li>
           <li><a href="cr_main.asp">Corporate Relations</a></li>
           <li><a href="outreach_main.asp">Outreach</a></li>
           <li><a href="pr_main.asp">Public Relations</a></li>
           <li><a href="student_services.asp">Student Services</a></li>
           <li><a href="finance.asp">Finance Forms</a></li>
           <li><a href="fundraising.asp">Fundraising</a></li>
           <li><a href="gsp_main.asp">Graduate Student Program</a></li>
           </ul>
</li>

<br />

<li><img src="imagesnew/formembers.png" alt=""" />
           <ul>
           <li><a href="get_involved.asp">Get Involved</a></li>
           <li><a href="scholarships.asp">Scholarship Opportunities</a></li>
           <li><a href="docs.asp">Documents</a></li>
           <li><a href="newsletter.asp">Newsletters</a></li>
           <li><a href="photos.asp">Photos</a></li>
           <li><a href="resources.asp">Resources</a></li>
           </ul>
</li>

<br />

<li><img src="imagesnew/foremployers.png" alt=""" />
           <ul>
           <li><a href="info_session.asp">Host An Information Session</a></li>
           <li><a href="pnd_main.asp">Professional Networking Dinner</a></li>
           <li><a href="support.asp">Support SWE</a></li>
           <li><a href="sponsors.asp">Our Sponsors</a></li>
           </ul>
</li>
</ul>


<br /><br /><br /><br /><br /><br />
</div> <!-- END CONTENTS LEFT DIV -->