<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>Cornell Society of Women Engineers</title>
	<link type="text/css" rel="stylesheet" href="stylesheet.css" />
</head>

<body>

<div id="container">

<div id="header">
<a href="index.asp"><img src='imagesnew/header.png' alt='header' align='left' border='0'/></a>
</div>

<div id="menu">
<ul>
<li><a href="index.asp">Home</a></li>
<li><a href="about_main.asp">About</a></li>
<li><a href="join.asp">Join SWE</a></li>
<li><a href="contact.asp">Contact Us</a></li>
</ul>
</div>

<div id="menu2">
<img src="imagesnew/banner_s.jpg" alt="banner" border="0"/>
</div>



<div id="sidebar">

<h2>Our Programs</h2>
 <ul>
           <li><a href="cd_main.asp">Career Development</a></li>
           <li><a href="cr_main.asp">Corporate Relations</a></li>
           <li><a href="outreach_main.asp">Outreach</a></li>
           <li><a href="pr_main.asp">Public Relations</a></li>
           <li><a href="student_services.asp">Student Services</a></li>
           <li><a href="finance.asp">Finance Forms</a></li>
           <li><a href="fundraising.asp">Fundraising</a></li>
           <li><a href="gsp_main.asp">Graduate Student Program</a></li>
           </ul>
		   
		   
		   <h2>For Members</h2>
		     <ul>
           <li><a href="get_involved.asp">Get Involved</a></li>
           <li><a href="scholarships.asp">Scholarship Opportunities</a></li>
           <li><a href="docs.asp">Documents</a></li>
           <li><a href="newsletter.asp">Newsletters</a></li>
           <li><a href="photos.asp">Photos</a></li>
           <li><a href="resources.asp">Resources</a></li>
		   <li><a href="http://facebook.com/groups/2200096715?ap=1">facebook group</a></li>
           </ul>
		   
		   
		   <h2>For Employers</h2>
		    <ul>
           <li><a href="info_session.asp">Host An Information Session</a></li>
           <li><a href="pnd_main.asp">Professional Networking Dinner</a></li>
           <li><a href="support.asp">Support SWE</a></li>
           <li><a href="sponsors.asp">Our Sponsors</a></li>
           </ul><br/>
</div>




<div id = "main">