<div id="sidebar">



<h2>News</h2>

<h4>SWE Section Award</h4>
We received an Outstanding Collegiate Section Gold award at the 2011 SWE Annual Conference! The conference was held October 13-15, 2011 in Chicago, Illinois.
<br/><br/>
<img src="imagesnew/award_home.png" alt="award"/>


<h4>Information Sessions</h4>
We have several information sessions coming up! Check the calendar for more details. 
<br/><br/><img src="imagesnew/is_th.png" alt="pnd"/>

   </div>

  

   
   <div id="videos"> 
<h2>Featured Podcasts</h2>
<div id="frame1">
<h4><center>SWEcast 1 - A Peek into ChemE</center></h4>
<iframe width="240" height="220" src="http://www.youtube.com/embed/rJW37tKCN5E" frameborder="0" allowfullscreen></iframe>
</div>

<div id="frame2">
<h4><center>SWEcast 2 - A Peek into BEE</center></h4>
<iframe width="240" height="220" src="http://www.youtube.com/embed/eA4MI16JcG8" frameborder="0" allowfullscreen></iframe>
</div>

<div id="frame3">
<h4><center>SWEcast 5 - A Peek into ORIE</center></h4>
<iframe width="240" height="220" src="http://www.youtube.com/embed/glOxK8awNfQ" frameborder="0" allowfullscreen></iframe>
</div>
<a href="http://www.youtube.com/user/CornellSWE">See More Videos</a>

   </div>
   
   
<div id="footer">

<center>If you have any questions, contact us at <a href="#">corswe@gmail.com</a></center>
<br/>

<div id="footer1">
<h5>CORNELL SWE</h5>
162 Olin Hall<br/>
 Ithaca NY<br/>14853<br/><br/>
<a href="feedback.asp">Feedback</a> <br/><br/>
<a href="http://facebook.com/groups/2200096715?ap=1"><img src="imagesnew/facebook.png" width="20" height="20" alt="Facebook" title="Cornell SWE Facebook Group"/></a>
<a href="http://www.linkedin.com/groups?viewMembers=&gid=2408656&sik=1317843674949"><img src="imagesnew/linkedin.png" width="20" height="20" alt="LinkedIn" title="Cornell SWE LinkedIn Group"/></a>
<a href="http://www.flickr.com/photos/cornell_swe/sets"><img src="imagesnew/flickr.png" width="20" height="20" alt="Flickr" title="Cornell SWE Flickr Photos" /></a>
<a href="http://www.youtube.com/user/CornellSWE"><img src="imagesnew/youtube.png" width="20" height="20" alt="YouTube" title="Cornell SWE YouTube" /></a>
</div>

<div id="footer2">
<h5>LINKS</h5>
<a href="about_main.asp">About Us</a><br/>
<a href="contact.asp">Contact Us</a><br/>
<a href="http://swedirectors.blogspot.com/">SWE Blogspot</a><br/>
<a href="http://www.engineering.cornell.edu/diversity/">Cornell DPE</a><br/>
<a href="http://www.swe.org/regione/">SWE Region E</a><br/>
<a href="http://societyofwomenengineers.swe.org/">swe.org</a>
</div>


<div id="footer3">
<h5>JOIN SWE</h5>
<a href="join.asp">Join Our Listserv</a><br/>
<a href="join.asp#meetings">G-Body Meetings</a><br/>
<a href="join.asp#nationalswe">National SWE</a><br/>
<a href="join.asp#chair">Become a Chair</a><br/>
<a href="join.asp#liaison">Become a Liaison</a><br/>
<a href="oin.asp#director">Become a Director</a><br/>
</div>

<div id="footer4">
<h5>UNDERGRADS</h5>
<a href="#">Get a Major</a><br/>
<a href="#">Get the "A"!</a><br/>
<a href="#">Get a Job/Internship</a><br/>
<a href="#">Get a Scholarship</a><br/>
<a href="#">Get into Grad School</a><br/>
<a href="#">Conferences</a><br/>
<a href="#">Merchandise</a><br/>
<a href="#">Outreach</a><br/>
<a href="#">Come Hang with Us!</a><br/>
<a href="#">For Chairs</a><br/> 
</div>


<div id="footer5">
<h5>GRAD STUDENTS</h5>
<a href="#">Outreach</a><br/>
<a href="#">Grad SWE Blog</a><br/>
<a href="#">Graduate Listserv</a><br/>
<a href="#">Conferences</a><br/>
<a href="#">Merchandise</a><br/>
</div>

<div id="footer6">
<h5>EMPLOYERS</h5>
<a href="resumefile.asp">Resume file</a><br/>
<a href="info_session.asp">Information Session</a><br/>
<a href="pnd_main.asp">Professional Networking Dinner</a><br/>
 <a href="sponsors.asp">Our Sponsors</a><br/>
<a href="fundraising.asp">Support Cornell SWE</a><br/>
</div>

<div id="footer7">
<h5>ALUMNI</h5>
<a href="alumni_join.asp">Alumni Listserv</a><br/>
<a href="ted.asp">TED Talk</a><br/>
<a href="map.asp">Destination Map</a><br/>
<a href="alumniresources.asp">Resources</a><br/>
</div>



</div>
</div> 

</body>
</html>
