<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>Cornell Society of Women Engineers</title>
	<link type="text/css" rel="stylesheet" href="teststylesheet.css" />
	<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<link rel="stylesheet" type="text/css" href="ddsmoothmenu.css" />
<link rel="stylesheet" type="text/css" href="ddsmoothmenu-v.css" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript" src="ddsmoothmenu.js">

/***********************************************
* Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/

</script>

<script type="text/javascript">

ddsmoothmenu.init({
	mainmenuid: "smoothmenu1", //menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu', //class added to menu's outer DIV
	//customtheme: ["#1c5a80", "#18374a"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

ddsmoothmenu.init({
	mainmenuid: "smoothmenu2", //Menu DIV id
	orientation: 'v', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu-v', //class added to menu's outer DIV
	//customtheme: ["#804000", "#482400"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

</script>
</head>

<body>

<div id="container">

<div id="menu2">
<a href="index.asp"><img src="imagesnew/header.png" alt="" border="0" id="topbanner" /></a><br /><br />

<div id="smoothmenu1" class="ddsmoothmenu">
<ul>
<li><a href="index.asp">Home</a></li>
<li><a href="#">About Us</a>
  <ul>
  <li><a href="#">About Us</a></li>
  <li><a href="#">Our Mission</a></li>
    <li><a href="#">Our Programs</a></li>
    <li><a href="#">EBoard</a></li>
  <li><a href="#">Awards</a></li>
  </ul>
</li>
<li><a href="#">Join Us</a>
  <ul>
  <li><a href="#">Join Our Listserv</a></li>
  <li><a href="#">G-Body Meetings</a></li>
  <li><a href="#">Join National SWE</a></li>
  <li><a href="#">Become a Chair</a></li>
  <li><a href="#">Become a Liaison</a></li>
  <li><a href="#">Become a Director</a></li>
  </ul>
</li>
<li><a href="#">Contact Us</a></li>
<li><a href="#">For Undergrads</a>
  <ul>
  <li><a href="#">Get a Major</a></li>
  <li><a href="#">Get the "A"! (Study Help)</a></li>
  <li><a href="#">Get a Job/Internship</a></li>
  <li><a href="#">Get a Scholarship</a></li>
  <li><a href="#">Get into Grad School</a></li>
    <li><a href="#">Conferences</a></li>
  <li><a href="#">Get SWE Merchandise</a></li>
  <li><a href="#">Volunteer with Outreach</a></li>
  <li><a href="#">Come Hang with Us! (Student Services)</a></li>
<li><a href="#">For Chairs</a></li> 
 </ul>
</li>
<li><a href="#">For Grad Students</a>
  <ul>
  <li><a href="#">Outreach</a></li>
  <li><a href="#">Cornell Graduate SWE Blog</a></li>
  <li><a href="#">Join Graduate SWE Mailing List</a></li>
    <li><a href="#">Conferences</a></li>
    <li><a href="#">Get SWE Merchandise</a></li>
 </ul>
</li>
<li><a href="#">For Alumni</a>
  <ul>
  <li><a href="#">Coming Soon!</a></li>
 </ul>
</li>
<li><a href="#">For Employers</a>
  <ul>
  <li><a href="#">Resume file</a></li>
   <li><a href="#">Host an Information Session</a></li>
   <li><a href="#">Professional Networking Dinner</a></li>
  <li><a href="#">Our Sponsors</a></li>
    <li><a href="#">Support Cornell SWE (Fundraising)</a></li>
	</ul>
</li>
</ul>
<br style="clear: left" />
</div>

<br/>
<img src="imagesnew/banner_new.png" alt="" />




</div>



<div id="sidebar">
<h2>About Us</h2>
  <ul>
  <li><a href="#">About Us</a></li>
  <li><a href="#">Our Mission</a></li>
    <li><a href="#">Our Programs</a></li>
    <li><a href="#">EBoard</a></li>
  <li><a href="#">Awards</a></li>
  </ul>
		   </div>




<div id = "main">