<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>Cornell Society of Women Engineers</title>
	<link type="text/css" rel="stylesheet" href="stylesheet_test.css" />
	<link rel="stylesheet" type="text/css" href="ddsmoothmenu.css" />
	<link rel="stylesheet" type="text/css" href="ddsmoothmenu-v.css" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
	<script type="text/javascript" src="ddsmoothmenu.js">
	/***********************************************
	* Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
	* This notice MUST stay intact for legal use
	* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
	***********************************************/
	</script>

	<script type="text/javascript">

	ddsmoothmenu.init({
		mainmenuid: "smoothmenu1", //menu DIV id
		orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
		classname: 'ddsmoothmenu', //class added to menu's outer DIV
		//customtheme: ["#1c5a80", "#18374a"],
		contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
	})

	ddsmoothmenu.init({
		mainmenuid: "smoothmenu2", //Menu DIV id
		orientation: 'v', //Horizontal or vertical menu: Set to "h" or "v"
		classname: 'ddsmoothmenu-v', //class added to menu's outer DIV
		//customtheme: ["#804000", "#482400"],
		contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
	})

	</script>
</head>

<body>



<div id="topcontainer">

<a href="index.asp">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>

<div id="toplinks">
<ul>
<li><a href="about_main.asp">About Us</a></li>
<li><a href="contact.asp">Contact Us</a></li>
<li><a href="http://swedirectors.blogspot.com/">Cornell SWE Blogspot</a></li>
<li><a href="http://www.engineering.cornell.edu/diversity/">Cornell DPE</a></li>
<li><a href="http://www.swe.org/regione/">SWE Region E</a></li>
<li><a href="http://societyofwomenengineers.swe.org/">swe.org</a></li>
<li><a href="http://facebook.com/groups/2200096715?ap=1"><img src="imagesnew/facebook.png" width="20" height="20" alt="Facebook" title="Cornell SWE Facebook Group"/></a>
<a href="http://www.linkedin.com/groups?viewMembers=&gid=2408656&sik=1317843674949"><img src="imagesnew/linkedin.png" width="20" height="20" alt="LinkedIn" title="Cornell SWE LinkedIn Group"/></a>
<a href="http://www.flickr.com/photos/cornell_swe/sets"><img src="imagesnew/flickr.png" width="20" height="20" alt="Flickr" title="Cornell SWE Flickr Photos" /></a>
<a href="http://www.youtube.com/user/CornellSWE"><img src="imagesnew/youtube.png" width="20" height="20" alt="YouTube" title="Cornell SWE YouTube" /></a></li>
</ul>
</div>

<div id="background">
<a href="index.asp"><img src="imagesnew/bg_logo_5.png" alt="home"/></a>
<a href="join.asp"><img src="imagesnew/join2.png" alt="join"/></a>
<a href="fundraising.asp"><img src="imagesnew/sponsor.png" alt="sponsor"/></a>
</div>


<div id="smoothmenu1" class="ddsmoothmenu">
<ul>


<li><a href="undergrads.asp">For Undergrads</a>
  <ul>
  <li><a href="major.asp">Get a Major</a></li>
  <li><a href="study.asp">Get the "A"!</a></li>
  <li><a href="jobs.asp">Get a Job or Internship</a></li>
  <li><a href="scholarships.asp">Get a Scholarship</a></li>
  <li><a href="gradschool.asp">Get into Grad School</a></li>
    <li><a href="conferences.asp">Conferences</a></li>
	  <li><a href="http://swe.cornell.edu/stress_relief/">Stress Relief</a></li>
  <li><a href="merchandise.asp">SWE Merchandise</a></li>
  <li><a href="outreach_main.asp">Volunteer with Outreach</a></li>
  <li><a href="student_services.asp">Come Hang with Us!</a></li>
<li><a href="chairs.asp">For Chairs</a></li> 
 </ul>
</li>
<li><a href="gradstudents.asp">For Grad Students</a>
  <ul>
  <li><a href="gradoutreach.asp">Outreach</a></li>
  <li><a href="http://www.graduateswe.blogspot.com/">Grad SWE Blog</a></li>
  <li><a href="gsp_main.asp">Grad SWE Mailing List</a></li>
    <li><a href="conferences.asp">Conferences</a></li>
	 <li><a href="http://swe.cornell.edu/stress_relief/">Stress Relief</a></li>
    <li><a href="merchandise.asp">SWE Merchandise</a></li>
 </ul>
</li>
<li><a href="employers.asp">For Employers</a>
  <ul>
  <li><a href="resumefile.asp">Resume file</a></li>
   <li><a href="info_session.asp">Host an Information Session</a></li>
   <li><a href="pnd_main.asp">Professional Networking Dinner</a></li>
  <li><a href="sponsors.asp">Our Sponsors</a></li>
    <li><a href="fundraising.asp">Support Cornell SWE - Fundraising</a></li>
	</ul>
</li>
<li><a href="alumni.asp">For Alumni</a>
  <ul>
<li><a href="alumni_join.asp">Join Alumni Listserv</a></li>
<li><a href="ted.asp">Host a TED Talk</a></li>
<li><a href="map.asp">Alumni Destinations Map</a></li>
<li><a href="alumniresources.asp">Resources for Registered Alumni</a></li>
 </ul>
</li>


</ul>
<br style="clear: left" />
</div>


</div>

<div id="container">


<img src="imagesnew/img1.png" alt="banner" />



<div id = "main">