<div class="header">
      <div class="row text-right">
        <div class="large-8 columns">
        </div>
        <div class="large-2 columns">
          <i class="fa fa-linkedin"></i>
          <i class="fa fa-flickr"></i>
          <i class="fa fa-twitter"></i>
          <i class="fa fa-facebook"></i>
        </div>
      </div>
    </div>
    <div class="contain-to-grid sticky">
        <nav class="top-bar" data-topbar>
          <ul class="title-area">
            <li class="divider"></li>
            <li class="name">
              <h1><a href=“/“>
                <img src="images/logo_gray.png" alt="">
              </a></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
          </ul>

            <section class="top-bar-section">
              <!-- Right Nav Section -->
              <ul class="left">
                <li class="has-dropdown">
                  <a href="#">About</a>
                  <ul class="dropdown">
                    <li><a href="eboard.asp">Executive Board</a></li>
                    <li><a href="directorships.asp">Directorships</a></li>
                    <li><a href="grad_programs.asp">Graduate Student Programs</a></li>
                    <li><a href="awards.asp">Awards</a></li>
                    <li><a href="conference.asp">Conference</a></li>
                    <li><a href="photos.asp">Photos</a></li>
                    <li><a href="outreach.asp">Outreach</a></li>
                  </ul>
                </li>
                <li class="has-dropdown">
                  <a href="#">Events</a>
                  <ul class="dropdown">
                    <li><a href="pnd.asp">Professional Networking Dinner</a></li>
                    <li><a href="welcome_picnic.asp">Welcome Picnic</a></li>
                    <li><a href="student_faculty_dinner.asp">Student-Faculty Dinner</a></li>
                    <li><a href="wie_wkend.asp">WIE Weekend</a></li>
                    <li><a href="diversity_wkend.asp">Diversity Weekend</a></li>
                    <li><a href="gbodies.asp">General Body Meetings</a></li>
                  </ul>
                </li>
                
                <li class="has-dropdown">
                  <a href="#">Employers</a>
                  <ul class="dropdown">
                    <li><a href="info_session.asp">Host an Information Session</a></li>
                    <li><a href="support.asp">Support SWE</a></li>
                    <li><a href="sponsors.asp">Our Sponsors</a></li>
                  </ul>
                </li>
                <li class="has-dropdown">
                  <a href="#">Members</a>
                    <ul class="dropdown">
                      <li><a href="get_involved.asp">Get Involved</a></li>
                      <li><a href="scholarships.asp">Scholarships</a></li>
                      <li><a href="merchandise.asp">Merchandise</a></li>
                      <li><a href="documents.asp">Documents</a></li>
                      <li><a href="resources.asp">Resources</a></li>
                      <li><a href="newsletters.asp">Newsletters</a></li>
                      <li><a href="podcasts.asp">Podcasts</a></li>
                    </ul>
                </li>
                <li>
                  <a id="search-button" href="javascript:search()">
                    <i class="fa fa-search"></i>
                  </a>
                  <div id="search">
                    <script>
                      (function() {
                        var cx = '009160791705554863868:tt1lxhfbdww';
                        var gcse = document.createElement('script');
                        gcse.type = 'text/javascript';
                        gcse.async = true;
                        gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
                            '//www.google.com/cse/cse.js?cx=' + cx;
                        var s = document.getElementsByTagName('script')[0];
                        s.parentNode.insertBefore(gcse, s);
                      })();
                    </script>
                    <gcse:search></gcse:search>
                  </div>
                </li>
              </ul>
              <ul class="right">
                <li class="divider"></li>
                <li class="has-form">
                  <a href="join.asp" class="button">
                    Join SWE
                  </a>
                </li>
                <li class="divider"></li>
              </ul>
          </section>
        </nav>
    </div>